# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Valgrind

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/extractions/setup-just
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up clang toolchain
        run: sudo apt-get install -y clang clang-tidy cmake lldb ninja-build

      - name: Install raylib dependencies
        run: sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev

      - name: Print PATH
        run: echo "$PATH"

      - name: Set up valgrind dependencies
        run: sudo apt-get install -y valgrind

      - name: Valgrind
        run: |
          valgrind --version
          just valgrind main
